# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.10-slim

WORKDIR /app

# Install runtime dependencies
COPY pyproject.toml uv.lock ./
# Install mcp server dependencies
RUN pip install --no-cache-dir httpx mcp[cli]

# Copy server code
COPY server.py ./

# Expose port if needed (stdio transport doesn't require HTTP port)

# Default command
CMD ["python", "server.py"]
